SELECT i.FLAVOR
FROM ICECREAM_INFO AS i
    LEFT JOIN FIRST_HALF AS f ON i.FLAVOR = f.FLAVOR
WHERE i.INGREDIENT_TYPE = 'fruit_based'
GROUP BY f.FLAVOR
HAVING SUM(F.TOTAL_ORDER) > 3000
ORDER BY SUM(f.TOTAL_ORDER) DESC;